server:
  port: 9091

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zuulGame
      username: root
      password: 159ly159
#  profiles:
#    active:

mybatis-plus:
 global-config:
   db-config:
     id-type: auto
 configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl